"""What Aut(A)-equivariance actually imposes.

T^A-naturality makes Psi_{n dim A} commute with phi_n = phi (x) id for every
phi in Aut(A).  That sounds like equivariance; it is much weaker, and one can say
exactly how weak.

E1.  IT IS TRIVIAL ON THE BASE.  Every automorphism is unital, phi(1) = 1, so phi_n
     fixes the real locus 1_A (x) R^n POINTWISE.  Since Psi_{n dim A} restricted to
     that locus is Psi_n, the condition says nothing whatever about the base method:
     its whole content is about the nilpotent directions.  At the Lie algebra level
     the same fact reads d(1) = 0 for every derivation, and d(m) is contained in m,
     so the matrix of d has zero e_0 row and column.

E2.  WHAT IT GENERATES IS gl(m-1), NOT gl(m).  Collecting the Aut-actions over ALL
     factorizations m = n dim A, the Lie algebra generated is exactly gl(m-1) acting
     on the nilpotent directions -- measured for m = 4, 6, 8 as 9, 25, 49 against
     gl(m) = 16, 36, 64, and against the stabilizer of e_0, which is larger still at
     m^2 - m.  It is already realized by the single algebra J^1_{m-1} =
     R[x_1..x_{m-1}]/m^2, whose automorphism group is GL(m-1), so combining
     factorizations gains nothing at all.

     This refines the recorded reason why coherence does not recover GL(n)-
     equivariance.  It is not (only) that the lifted locus is too thin: the group is
     the wrong group.  It fixes the base pointwise, so no amount of it can ever
     produce equivariance in the R^n directions.  An earlier pass recorded "the
     group generated is large enough (gl(nN))"; for the automorphism-generated group
     that is false.

E3.  WHAT IT DOES IMPOSE.  For A = J^1_k the lift is the k-fold Whitney sum,
     X^A(u^0, u^1, ..., u^k) = (X(u^0), DX(u^0)u^1, ..., DX(u^0)u^k), and Aut(A) =
     GL(k) mixes the k tangent copies.  So the content of the condition is exactly:
     Psi may not distinguish directions inside the nilpotent part -- no preferred
     basis of m -- and nothing else.
"""
from fractions import Fraction as F
from poly import P
import algebra as al
from algebra import ALGEBRAS
from test_affine import gen_map, euler


def rank(rows, w):
    R = [r[:] for r in rows]; r = 0
    for c in range(w):
        p = next((i for i in range(r, len(R)) if R[i][c]), None)
        if p is None: continue
        R[r], R[p] = R[p], R[r]; pv = R[r][c]
        for i in range(len(R)):
            if i != r and R[i][c]:
                f = R[i][c] / pv; R[i] = [R[i][j] - f * R[r][j] for j in range(w)]
        r += 1
    return r


def kills_unit():
    ok = True
    print("  E1  Der(A), and every derivation kills the unit")
    print("      based algebra                    dim Der   d(1) = 0   d(m) in m")
    for _, lst in sorted(ALGEBRAS.items()):
        for A in lst:
            Dr = al.derivations(A)
            k1 = all(sum(A.one[a] * d[g * A.N + a] for a in range(A.N)) == 0
                     for d in Dr for g in range(A.N))
            # d(m) in m, i.e. zero e_0-row, only meaningful when 1 = e_0
            uf = (A.one == [F(1)] + [F(0)] * (A.N - 1))
            mm = (not uf) or all(d[0 * A.N + a] == 0 for d in Dr for a in range(A.N))
            ok &= k1 and mm
            print(f"      {A.name:32s} {len(Dr):5d}      {str(k1):8s}   {mm}")
    print("      -> Aut(A) fixes the real locus 1_A (x) R^n pointwise, so the condition")
    print("         imposes nothing on Psi_n: its content is entirely in the fibre.")
    return ok


def generated():
    ok = True
    print("\n  E2  the Lie algebra generated by all Aut-actions over the factorizations")
    print("      m   dim generated   gl(m-1)   stab(e_0)   gl(m)")
    for m in (4, 6):
        gens = []
        for n in range(1, m + 1):
            if m % n: continue
            N = m // n
            pool = list(ALGEBRAS.get(N, [])) + ([al.Wk(N - 1), al.Jr(N - 1)] if N >= 2 else [])
            for A in pool:
                for d in al.derivations(A):
                    M = [[F(0)] * m for _ in range(m)]
                    for j in range(n):
                        for g in range(N):
                            for a in range(N): M[j * N + g][j * N + a] = d[g * N + a]
                    gens.append([x for row in M for x in row])
        basis = []
        for g in gens:
            if rank(basis + [g], m * m) > len(basis): basis.append(g)
        changed = True
        while changed:
            changed = False
            for i in range(len(basis)):
                for j in range(i + 1, len(basis)):
                    A_, B_ = basis[i], basis[j]
                    a2 = [A_[r * m:(r + 1) * m] for r in range(m)]
                    b2 = [B_[r * m:(r + 1) * m] for r in range(m)]
                    c = [sum(a2[r][k] * b2[k][cc] - b2[r][k] * a2[k][cc] for k in range(m))
                         for r in range(m) for cc in range(m)]
                    if any(c) and rank(basis + [c], m * m) > len(basis):
                        basis.append(c); changed = True
        good = (len(basis) == (m - 1) ** 2)
        ok &= good
        print(f"      {m}   {len(basis):13d}   {(m-1)**2:7d}   {m*m-m:9d}   {m*m:5d}"
              + ("" if good else "   <-- UNEXPECTED"))
    print("      (m = 8 checked separately: 49 = gl(7), against gl(8) = 64)")
    print("      -> exactly gl(m-1), realized already by J^1_{m-1} alone.  The group")
    print("         fixes the base pointwise, so it can never give GL(n) there.")
    return ok


def whitney():
    ok = True
    n, Ms, k = 2, 3, 2
    A = al.Wk(k)                                  # J^1_2, Aut = GL(2)
    X = gen_map(n, Ms, 3)
    XA = al.lift_map(A, n, X, Ms, hs=n)
    m = n * A.N
    want = []
    for j in range(n):
        want.append(al.subs(X[j], [P.var(m + 1, i * 3) for i in range(n)] + [P.var(m + 1, m)], m + 1))
        for c in (1, 2):
            want.append(sum((al.subs(X[j].diff(i), [P.var(m + 1, t * 3) for t in range(n)]
                                     + [P.var(m + 1, m)], m + 1) * P.var(m + 1, i * 3 + c)
                             for i in range(n)), P(m + 1)))
    good = (XA == want)
    ok &= good
    print("\n  E3  the J^1_k-lift is the k-fold Whitney sum, (X, DX.u^1, ..., DX.u^k):"
          f" {good}" + ("" if good else "   <-- UNEXPECTED"))
    print("      and Aut(J^1_k) = GL(k) mixes the k tangent copies (test_relations D3),")
    print("      so the imposition is: no preferred basis of the nilpotent directions.")
    return ok


def main():
    return kills_unit() & generated() & whitney()


if __name__ == "__main__": raise SystemExit(0 if main() else 1)
